name: Gradle Package

on:
    pull_request:
        branches:
            - release

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'corretto'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

            - name: Build with Gradle Wrapper
              run: ./gradlew build

            - name: Check if version already exists
              id: check_version
              run: |
                version=$(./gradlew -q getVersion)
                echo "Checking if version $version already exists..."
                curl -sSL -H "Authorization: token $GITHUB_TOKEN" "https://maven.pkg.github.com/pedrojschmidt/print-script/com/example/my-package/$version/maven-metadata.xml" > metadata.xml
                if grep -q "<version>$version</version>" metadata.xml; then
                  echo "Version $version already exists."
                  exit 1
                else
                  echo "Version $version does not exist yet."
                fi

            - name: Publish to GitHub Packages
              run: ./gradlew publish
              env:
                GITHUB_TOKEN: ${{ secrets.PRINTSCRIPT_TOKEN }}
